"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import psycopg, dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f!qr+*89vq-g6xok8q924-ri3shgcpce3s362r693#(3+_a0=q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',  # Add your app here
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'prisma.qugdnavujrpjlflpxotj',
        'PASSWORD': 'connection_to_database',
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',
        'PORT': '5432',
    },
    'users': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'prisma.qugdnavujrpjlflpxotj',
        'PASSWORD': 'connection_to_database',
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=user_d'  # Ensure queries look in the 'social' schema
        },
    },
    'social': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'prisma.qugdnavujrpjlflpxotj',
        'PASSWORD': 'connection_to_database',
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=social'  # Ensure queries look in the 'social' schema
        },
    },
    'items': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'prisma.qugdnavujrpjlflpxotj',
        'PASSWORD': 'connection_to_database',
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=items_d'  # Ensure queries look in the 'social' schema
        },
    },
    'audit': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'prisma.qugdnavujrpjlflpxotj',
        'PASSWORD': 'connection_to_database',
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=audit'  # Ensure queries look in the 'social' schema
        },
    },
    'groups': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'prisma.qugdnavujrpjlflpxotj',
        'PASSWORD': 'connection_to_database',
        'HOST': 'aws-0-eu-north-1.pooler.supabase.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=community'  # Ensure queries look in the 'social' schema
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # or wherever your frontend is hosted
]