export const COUNTRIES: { name: string; value: string }[] = [
    { name: "Algeria", value: "algeria" },
    { name: "Argentina", value: "argentina" },
    { name: "Australia", value: "australia" },
    { name: "Bangladesh", value: "bangladesh" },
    { name: "Brazil", value: "brazil" },
    { name: "Canada", value: "canada" },
    { name: "Chile", value: "chile" },
    { name: "China", value: "china" },
    { name: "Colombia", value: "colombia" },
    { name: "Cuba", value: "cuba" },
    { name: "Dominican Republic", value: "dominican_republic" },
    { name: "Egypt", value: "egypt" },
    { name: "Ecuador", value: "ecuador" },
    { name: "Ethiopia", value: "ethiopia" },
    { name: "Fiji", value: "fiji" },
    { name: "France", value: "france" },
    { name: "Germany", value: "germany" },
    { name: "Ghana", value: "ghana" },
    { name: "Guatemala", value: "guatemala" },
    { name: "Haiti", value: "haiti" },
    { name: "India", value: "india" },
    { name: "Indonesia", value: "indonesia" },
    { name: "Italy", value: "italy" },
    { name: "Japan", value: "japan" },
    { name: "Jamaica", value: "jamaica" },
    { name: "Kenya", value: "kenya" },
    { name: "Kiribati", value: "kiribati" },
    { name: "Mexico", value: "mexico" },
    { name: "Morocco", value: "morocco" },
    { name: "Netherlands", value: "netherlands" },
    { name: "Nigeria", value: "nigeria" },
    { name: "Norway", value: "norway" },
    { name: "Pakistan", value: "pakistan" },
    { name: "Palau", value: "palau" },
    { name: "Panama", value: "panama" },
    { name: "Papua New Guinea", value: "papua_new_guinea" },
    { name: "Paraguay", value: "paraguay" },
    { name: "Peru", value: "peru" },
    { name: "Philippines", value: "philippines" },
    { name: "Poland", value: "poland" },
    { name: "Samoa", value: "samoa" },
    { name: "Solomon Islands", value: "solomon_islands" },
    { name: "South Africa", value: "south_africa" },
    { name: "South Korea", value: "south_korea" },
    { name: "Spain", value: "spain" },
    { name: "Sweden", value: "sweden" },
    { name: "Switzerland", value: "switzerland" },
    { name: "Tanzania", value: "tanzania" },
    { name: "Thailand", value: "thailand" },
    { name: "Trinidad & Tobago", value: "trinidad_tobago" },
    { name: "Tonga", value: "tonga" },
    { name: "Uganda", value: "uganda" },
    { name: "United Kingdom", value: "uk" },
    { name: "United States", value: "usa" },
    { name: "Uruguay", value: "uruguay" },
    { name: "Vanuatu", value: "vanuatu" },
    { name: "Vietnam", value: "vietnam" }
  ]